name: Manual release -> build & push to Docker Hub

permissions:
  contents: write

on:
    workflow_dispatch: {}

jobs:
    create-release:
      name: Create release tag
      runs-on: ubuntu-latest
      outputs:
        new-tag-version: ${{ steps.ccv.outputs.new-tag-version }}
        new-tag-created: ${{ steps.ccv.outputs.new-tag }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Bump tag if necessary
          id: ccv
          uses: smlx/ccv@v0.10.0
        - name: Create GitHub Release
          if: steps.ccv.outputs.new-tag == 'true'
          uses: ncipollo/release-action@v1.20.0
          with:
            tag: ${{ steps.ccv.outputs.new-tag-version }}
            name: ${{ steps.ccv.outputs.new-tag-version }}
            generateReleaseNotes: true
            draft: false
            prerelease: false
    build-and-push:
        name: Build & push Docker images (manual)
        runs-on: ubuntu-latest
        needs: create-release
        if: github.actor == 'ChapterSevenSeeds' && needs.create-release.outputs.new-tag-created == 'true'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ needs.create-release.outputs.new-tag-version }}

            - name: Set up Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push images to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ${{ vars.DOCKERHUB_USERNAME }}/truenas-jobs-caldav-sync:${{ needs.create-release.outputs.new-tag-version }}
                      ${{ vars.DOCKERHUB_USERNAME }}/truenas-jobs-caldav-sync:latest
