name: PR â€” lint & build (no push)

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lint:
    name: Lint (Python example)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse python version from .python-version
        id: parse_pyproject
        run: |
          python_version=$(cat .python-version)
          echo "python_version=$python_version" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4

      - uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: src
          python-version: ${{ steps.parse_pyproject.outputs.python_version }}

  build-image:
    name: Does the Docker image build?
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: |
            test-${{ github.sha }}
