name: Release-bump

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    name: Create release tag (release-please)
    runs-on: ubuntu-latest
    steps:
      - name: install autotag binary
        run: |
          curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin
      - name: increment version
        run: |
          autotag --scheme=conventional
